In [4]:
import pandas as pd

In [5]:
df = pd.DataFrame({
    "name": ["Ali", "Sara", "Ahmed", "Ali"],
    "age": [22, 25, None, 22],
    "salary": [50000, 70000, 45000, 50000]
})

In [3]:
df.describe()

             age        salary
count   3.000000      4.000000
mean   23.000000  53750.000000
std     1.732051  11086.778913
min    22.000000  45000.000000
25%    22.000000  48750.000000
50%    22.000000  50000.000000
75%    23.500000  55000.000000
max    25.000000  70000.000000

In [5]:
df.shape

(4, 3)

In [6]:
df.dtypes

name       object
age       float64
salary      int64
dtype: object

In [7]:
df.isna().sum()

name      0
age       1
salary    0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(1)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   age     3 non-null      float64
 2   salary  4 non-null      int64
dtypes: float64(1), int64(1), object(1)
memory usage: 228.0+ bytes

In [10]:
df.isna().sum() / len(df) * 100

name       0.0
age       25.0
salary     0.0
dtype: float64

In [11]:
def missing_percentage(df):
    mp = df.isna().sum() / len(df) * 100
    return mp

In [13]:
print(missing_percentage(df));

name       0.0
age       25.0
salary     0.0
dtype: float64

In [14]:
def missing_severity(percent):

    if percent == 0:
        return "None"

    elif percent <= 5:
        return "LOW"

    elif percent <= 20:
        return "MEDIUM"

    else:
        return "HIGH"

In [16]:
missing_severity(0)

'None'

In [17]:
missing_severity(3)

'LOW'

In [18]:
missing_severity(8)

'MEDIUM'

In [19]:
missing_severity(25)

'HIGH'

In [20]:
for column in df.columns:
    print(column)

name
age
salary

In [21]:
for column in df.columns:
    missing = df[column].isna().sum()
    print(column, missing)

name 0
age 1
salary 0

In [24]:
for column in df.columns:
    missing = df[column].isna().sum()
    percentage = missing / len(df) * 100
    print(column, missing, percentage)

name 0 0.0
age 1 25.0
salary 0 0.0

In [34]:
def quality_report(df):
    print("=" * 50)
    print("DFINSIGHT REPORT")
    print("=" * 50)

    print("\nDATASET")
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])

    print("\nDATA TYPES")
    print(df.dtypes)

    print("\nMISSING VALUES")
    print(df.isna().sum())

    print("\nMISSING PERCENTAGE")
    print(missing_percentage(df))

    print("\nDUPLICATE ROWS")
    print(df.duplicated().sum())

    print("\nNUMERIC SUMMARY")
    print(df.describe())

    print("\nISSUES DETECTED")

    for column in df.columns:
        missing = df[column].isna().sum()

        if missing > 0:
            percentage = missing / len(df) * 100
            severity = missing_severity(percentage)

            print(
                f"- Missing values in '{column}': "
                f"{missing} ({percentage:.1f}%) "
                f"[{severity}]"
            )

    duplicates = df.duplicated().sum()

    if duplicates > 0:
        print(f"- Duplicate rows detected: {duplicates}")

    print("\n" + "=" * 50)

In [26]:
quality_report(df)

==================================================
DFINSIGHT REPORT
==================================================

DATASET
Rows: 4
Columns: 3

DATA TYPES
name       object
age       float64
salary      int64
dtype: object

MISSING VALUES
name      0
age       1
salary    0
dtype: int64

MISSING PERCENTAGE
name       0.0
age       25.0
salary     0.0
dtype: float64

DUPLICATE ROWS
1

NUMERIC SUMMARY
             age        salary
count   3.000000      4.000000
mean   23.000000  53750.000000
std     1.732051  11086.778913
min    22.000000  45000.000000
25%    22.000000  48750.000000
50%    22.000000  50000.000000
75%    23.500000  55000.000000
max    25.000000  70000.000000

==================================================

In [35]:
bad_df = pd.DataFrame({
    "name": ["Ali", "Sara", "Ahmed", "Ali", None],
    "age": [22, None, 150, 25, None],
    "salary": [50000, 70000, None, 50000, 70000]
})

In [36]:
quality_report(bad_df)

==================================================
DFINSIGHT REPORT
==================================================

DATASET
Rows: 5
Columns: 3

DATA TYPES
name       object
age       float64
salary    float64
dtype: object

MISSING VALUES
name      1
age       2
salary    1
dtype: int64

MISSING PERCENTAGE
name      20.0
age       40.0
salary    20.0
dtype: float64

DUPLICATE ROWS
0

NUMERIC SUMMARY
              age        salary
count    3.000000      4.000000
mean    65.666667  60000.000000
std     73.050211  11547.005384
min     22.000000  50000.000000
25%     23.500000  50000.000000
50%     25.000000  60000.000000
75%     87.500000  70000.000000
max    150.000000  70000.000000

ISSUES DETECTED
- Missing values in 'name': 1 (20.0%) [MEDIUM]
- Missing values in 'age': 2 (40.0%) [HIGH]
- Missing values in 'salary': 1 (20.0%) [MEDIUM]

==================================================

In [37]:
normal_df = pd.DataFrame({
    "name": ["Ali", "Sara", "Ahmed"],
    "age": [22, 25, 30],
    "salary": [50000, 70000, 60000]
})

In [38]:
quality_report(normal_df)

==================================================
DFINSIGHT REPORT
==================================================

DATASET
Rows: 3
Columns: 3

DATA TYPES
name      object
age        int64
salary     int64
dtype: object

MISSING VALUES
name      0
age       0
salary    0
dtype: int64

MISSING PERCENTAGE
name      0.0
age       0.0
salary    0.0
dtype: float64

DUPLICATE ROWS
0

NUMERIC SUMMARY
             age   salary
count   3.000000      3.0
mean   25.666667  60000.0
std     4.041452  10000.0
min    22.000000  50000.0
25%    23.500000  55000.0
50%    25.000000  60000.0
75%    27.500000  65000.0
max    30.000000  70000.0

ISSUES DETECTED

==================================================

In [39]:
duplicate_df = pd.DataFrame({
    "name": ["Ali", "Sara", "Ali"],
    "age": [22, 25, 22],
    "salary": [50000, 70000, 50000]
})

In [40]:
quality_report(duplicate_df)

==================================================
DFINSIGHT REPORT
==================================================

DATASET
Rows: 3
Columns: 3

DATA TYPES
name      object
age        int64
salary     int64
dtype: object

MISSING VALUES
name      0
age       0
salary    0
dtype: int64

MISSING PERCENTAGE
name      0.0
age       0.0
salary    0.0
dtype: float64

DUPLICATE ROWS
1

NUMERIC SUMMARY
             age        salary
count   3.000000      3.000000
mean   23.000000  56666.666667
std     1.732051  11547.005384
min    22.000000  50000.000000
25%    22.000000  50000.000000
50%    22.000000  50000.000000
75%    23.500000  60000.000000
max    25.000000  70000.000000

ISSUES DETECTED
- Duplicate rows detected: 1

==================================================

In [41]:
missing_df = pd.DataFrame({
    "name": [None, None, None, None],
    "age": [None, None, None, None],
    "salary": [None, None, None, None]
})

In [42]:
quality_report(missing_df)

==================================================
DFINSIGHT REPORT
==================================================

DATASET
Rows: 4
Columns: 3

DATA TYPES
name      object
age       object
salary    object
dtype: object

MISSING VALUES
name      4
age       4
salary    4
dtype: int64

MISSING PERCENTAGE
name      100.0
age       100.0
salary    100.0
dtype: float64

DUPLICATE ROWS
3

NUMERIC SUMMARY
       name  age salary
count     0    0      0
unique    0    0      0
top     NaN  NaN    NaN
freq    NaN  NaN    NaN

ISSUES DETECTED
- Missing values in 'name': 4 (100.0%) [HIGH]
- Missing values in 'age': 4 (100.0%) [HIGH]
- Missing values in 'salary': 4 (100.0%) [HIGH]
- Duplicate rows detected: 3

==================================================

In [43]:
import os

os.makedirs("dfinsight/src/dfinsight", exist_ok=True)
os.makedirs("dfinsight/tests", exist_ok=True)

print("Project structure created.")

Project structure created.

In [44]:
!find dfinsight -type f -o -type d

dfinsight
dfinsight/src
dfinsight/src/dfinsight
dfinsight/tests

In [45]:
%%writefile dfinsight/src/dfinsight/report.py

import pandas as pd


def missing_percentage(df):
    mp = df.isna().sum() / len(df) * 100
    return mp


def missing_severity(percent):

    if percent == 0:
        return "None"

    elif percent <= 5:
        return "LOW"

    elif percent <= 20:
        return "MEDIUM"

    else:
        return "HIGH"


def quality_report(df):
    print("=" * 50)
    print("DFINSIGHT REPORT")
    print("=" * 50)

    print("\nDATASET")
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])

    print("\nDATA TYPES")
    print(df.dtypes)

    print("\nMISSING VALUES")
    print(df.isna().sum())

    print("\nMISSING PERCENTAGE")
    print(missing_percentage(df))

    print("\nDUPLICATE ROWS")
    print(df.duplicated().sum())

    print("\nNUMERIC SUMMARY")
    print(df.describe())

    print("\nISSUES DETECTED")

    for column in df.columns:
        missing = df[column].isna().sum()

        if missing > 0:
            percentage = missing / len(df) * 100
            severity = missing_severity(percentage)

            print(
                f"- Missing values in '{column}': "
                f"{missing} ({percentage:.1f}%) "
                f"[{severity}]"
            )

    duplicates = df.duplicated().sum()

    if duplicates > 0:
        print(f"- Duplicate rows detected: {duplicates}")

    print("\n" + "=" * 50)

Writing dfinsight/src/dfinsight/report.py

In [46]:
%%writefile dfinsight/src/dfinsight/__init__.py

from .report import quality_report, missing_percentage, missing_severity

Writing dfinsight/src/dfinsight/__init__.py

In [47]:
!find dfinsight -type f

dfinsight/src/dfinsight/__init__.py
dfinsight/src/dfinsight/report.py

In [48]:
import sys

sys.path.insert(0, "dfinsight/src")

from dfinsight import quality_report

In [49]:
quality_report(bad_df)

==================================================
DFINSIGHT REPORT
==================================================

DATASET
Rows: 5
Columns: 3

DATA TYPES
name       object
age       float64
salary    float64
dtype: object

MISSING VALUES
name      1
age       2
salary    1
dtype: int64

MISSING PERCENTAGE
name      20.0
age       40.0
salary    20.0
dtype: float64

DUPLICATE ROWS
0

NUMERIC SUMMARY
              age        salary
count    3.000000      4.000000
mean    65.666667  60000.000000
std     73.050211  11547.005384
min     22.000000  50000.000000
25%     23.500000  50000.000000
50%     25.000000  60000.000000
75%     87.500000  70000.000000
max    150.000000  70000.000000

ISSUES DETECTED
- Missing values in 'name': 1 (20.0%) [MEDIUM]
- Missing values in 'age': 2 (40.0%) [HIGH]
- Missing values in 'salary': 1 (20.0%) [MEDIUM]

==================================================

In [50]:
%%writefile dfinsight/pyproject.toml

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "dfinsight"
version = "0.1.0"
description = "A lightweight data quality and dataset inspection library for pandas DataFrames"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pandas>=1.5"
]

Writing dfinsight/pyproject.toml

In [51]:
%%writefile dfinsight/README.md

# dfinsight

A lightweight Python library for initial dataset inspection and basic data-quality assessment using pandas.

## Features

- Dataset dimensions
- Data types
- Missing-value counts
- Missing-value percentages
- Missing-value severity
- Duplicate-row detection
- Numeric summary
- Basic issue detection

## Example

```python
import pandas as pd
from dfinsight import quality_report

df = pd.read_csv("data.csv")

quality_report(df)

Writing dfinsight/README.md

In [52]:
!cat dfinsight/README.md

# dfinsight

A lightweight Python library for initial dataset inspection and basic data-quality assessment using pandas.

## Features

- Dataset dimensions
- Data types
- Missing-value counts
- Missing-value percentages
- Missing-value severity
- Duplicate-row detection
- Numeric summary
- Basic issue detection

## Example

```python
import pandas as pd
from dfinsight import quality_report

df = pd.read_csv("data.csv")

quality_report(df)

In [53]:
!cat dfinsight/pyproject.toml

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "dfinsight"
version = "0.1.0"
description = "A lightweight data quality and dataset inspection library for pandas DataFrames"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pandas>=1.5"
]

In [54]:
!pip install build

Collecting build
  Downloading build-1.6.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.13/dist-packages (from build) (26.3)
Collecting pyproject_hooks (from build)
  Downloading pyproject_hooks-1.3.3-py3-none-any.whl.metadata (1.3 kB)
Downloading build-1.6.1-py3-none-any.whl (31 kB)
Downloading pyproject_hooks-1.3.3-py3-none-any.whl (10 kB)
Installing collected packages: pyproject_hooks, build
Successfully installed build-1.6.1 pyproject_hooks-1.3.3

In [55]:
!python -m build dfinsight

* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - setuptools>=61
* Getting build dependencies for sdist...
running egg_info
creating src/dfinsight.egg-info
writing src/dfinsight.egg-info/PKG-INFO
writing dependency_links to src/dfinsight.egg-info/dependency_links.txt
writing requirements to src/dfinsight.egg-info/requires.txt
writing top-level names to src/dfinsight.egg-info/top_level.txt
writing manifest file 'src/dfinsight.egg-info/SOURCES.txt'
reading manifest file 'src/dfinsight.egg-info/SOURCES.txt'
writing manifest file 'src/dfinsight.egg-info/SOURCES.txt'
* Installed build dependency versions:
  - setuptools==84.0.0
* Building sdist...
running sdist
running egg_info
writing src/dfinsight.egg-info/PKG-INFO
writing dependency_links to src/dfinsight.egg-info/dependency_links.txt
writing requirements to src/dfinsight.egg-info/requires.txt
writing top-level names to src/dfinsight.egg-info/top_level.txt
reading manifest file 'src/dfinsight.egg-info/SOURCES.txt'
writing manifest file 'src/dfinsight.egg-info/SOURCES.txt'
running check
creating dfinsight-0.1.0
creating dfinsight-0.1.0/src/dfinsight
creating dfinsight-0.1.0/src/dfinsight.egg-info
copying files to dfinsight-0.1.0...
copying README.md -> dfinsight-0.1.0
copying pyproject.toml -> dfinsight-0.1.0
copying src/dfinsight/__init__.py -> dfinsight-0.1.0/src/dfinsight
copying src/dfinsight/report.py -> dfinsight-0.1.0/src/dfinsight
copying src/dfinsight.egg-info/PKG-INFO -> dfinsight-0.1.0/src/dfinsight.egg-info
copying src/dfinsight.egg-info/SOURCES.txt -> dfinsight-0.1.0/src/dfinsight.egg-info
copying src/dfinsight.egg-info/dependency_links.txt -> dfinsight-0.1.0/src/dfinsight.egg-info
copying src/dfinsight.egg-info/requires.txt -> dfinsight-0.1.0/src/dfinsight.egg-info
copying src/dfinsight.egg-info/top_level.txt -> dfinsight-0.1.0/src/dfinsight.egg-info
Writing dfinsight-0.1.0/setup.cfg
Creating tar archive
removing 'dfinsight-0.1.0' (and everything under it)
* Building wheel from sdist
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - setuptools>=61
* Getting build dependencies for wheel...
running egg_info
writing src/dfinsight.egg-info/PKG-INFO
writing dependency_links to src/dfinsight.egg-info/dependency_links.txt
writing requirements to src/dfinsight.egg-info/requires.txt
writing top-level names to src/dfinsight.egg-info/top_level.txt
reading manifest file 'src/dfinsight.egg-info/SOURCES.txt'
writing manifest file 'src/dfinsight.egg-info/SOURCES.txt'
* Installed build dependency versions:
  - setuptools==84.0.0
* Building wheel...
running bdist_wheel
running build
running build_py
creating build/lib/dfinsight
copying src/dfinsight/__init__.py -> build/lib/dfinsight
copying src/dfinsight/report.py -> build/lib/dfinsight
running egg_info
writing src/dfinsight.egg-info/PKG-INFO
writing dependency_links to src/dfinsight.egg-info/dependency_links.txt
writing requirements to src/dfinsight.egg-info/requires.txt
writing top-level names to src/dfinsight.egg-info/top_level.txt
reading manifest file 'src/dfinsight.egg-info/SOURCES.txt'
writing manifest file 'src/dfinsight.egg-info/SOURCES.txt'
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/dfinsight
copying build/lib/dfinsight/__init__.py -> build/bdist.linux-x86_64/wheel/./dfinsight
copying build/lib/dfinsight/report.py -> build/bdist.linux-x86_64/wheel/./dfinsight
running install_egg_info
Copying src/dfinsight.egg-info to build/bdist.linux-x86_64/wheel/./dfinsight-0.1.0-py3.13.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/dfinsight-0.1.0.dist-info/WHEEL
creating '/content/dfinsight/dist/.tmp-89ip6t3x/dfinsight-0.1.0-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'dfinsight/__init__.py'
adding 'dfinsight/report.py'
adding 'dfinsight-0.1.0.dist-info/METADATA'
adding 'dfinsight-0.1.0.dist-info/WHEEL'
adding 'dfinsight-0.1.0.dist-info/top_level.txt'
adding 'dfinsight-0.1.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Successfully built dfinsight-0.1.0.tar.gz and dfinsight-0.1.0-py3-none-any.whl

In [56]:
!pip install dfinsight/dist/dfinsight-0.1.0-py3-none-any.whl --force-reinstall

Processing ./dfinsight/dist/dfinsight-0.1.0-py3-none-any.whl
Collecting pandas>=1.5 (from dfinsight==0.1.0)
  Downloading pandas-3.0.6-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 3.3 MB/s eta 0:00:00
Collecting numpy>=1.26.0 (from pandas>=1.5->dfinsight==0.1.0)
  Downloading numpy-2.5.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting python-dateutil>=2.8.2 (from pandas>=1.5->dfinsight==0.1.0)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas>=1.5->dfinsight==0.1.0)
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Downloading pandas-3.0.6-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 97.7 MB/s eta 0:00:00
Downloading numpy-2.5.3-cp313-cp313-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 103.4 MB/s eta 0:00:00
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 19.8 MB/s eta 0:00:00
Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six, numpy, python-dateutil, pandas, dfinsight
  Attempting uninstall: six
    Found existing installation: six 1.17.0
    Uninstalling six-1.17.0:
      Successfully uninstalled six-1.17.0
  Attempting uninstall: numpy
    Found existing installation: numpy 2.1.3
    Uninstalling numpy-2.1.3:
      Successfully uninstalled numpy-2.1.3
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.9.0.post0
    Uninstalling python-dateutil-2.9.0.post0:
      Successfully uninstalled python-dateutil-2.9.0.post0
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.3
    Uninstalling pandas-2.2.3:
      Successfully uninstalled pandas-2.2.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.3, but you have pandas 3.0.6 which is incompatible.
numba 0.61.2 requires numpy<2.3,>=1.24, but you have numpy 2.5.3 which is incompatible.
Successfully installed dfinsight-0.1.0 numpy-2.5.3 pandas-3.0.6 python-dateutil-2.9.0.post0 six-1.17.0

In [1]:
import dfinsight

print(dfinsight)
print(dfinsight.quality_report)

<module 'dfinsight' from '/usr/local/lib/python3.13/dist-packages/dfinsight/__init__.py'>
<function quality_report at 0x7ef1b4fe96c0>

In [6]:
from dfinsight import quality_report

quality_report(df)

==================================================
DFINSIGHT REPORT
==================================================

DATASET
Rows: 4
Columns: 3

DATA TYPES
name          str
age       float64
salary      int64
dtype: object

MISSING VALUES
name      0
age       1
salary    0
dtype: int64

MISSING PERCENTAGE
name       0.0
age       25.0
salary     0.0
dtype: float64

DUPLICATE ROWS
1

NUMERIC SUMMARY
             age        salary
count   3.000000      4.000000
mean   23.000000  53750.000000
std     1.732051  11086.778913
min    22.000000  45000.000000
25%    22.000000  48750.000000
50%    22.000000  50000.000000
75%    23.500000  55000.000000
max    25.000000  70000.000000

ISSUES DETECTED
- Missing values in 'age': 1 (25.0%) [HIGH]
- Duplicate rows detected: 1

==================================================

In [7]:
%%writefile dfinsight/tests/test_report.py

import pandas as pd

from dfinsight import missing_percentage, missing_severity


def test_missing_percentage():
    df = pd.DataFrame({
        "age": [20, None, 30, 40]
    })

    result = missing_percentage(df)

    assert result["age"] == 25.0


def test_missing_severity():
    assert missing_severity(0) == "None"
    assert missing_severity(3) == "LOW"
    assert missing_severity(10) == "MEDIUM"
    assert missing_severity(40) == "HIGH"

Writing dfinsight/tests/test_report.py

In [8]:
!pip install pytest

Requirement already satisfied: pytest in /usr/local/lib/python3.13/dist-packages (8.4.2)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.13/dist-packages (from pytest) (2.3.0)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.13/dist-packages (from pytest) (26.3)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.13/dist-packages (from pytest) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /usr/local/lib/python3.13/dist-packages (from pytest) (2.21.0)

In [9]:
!pytest dfinsight/tests -v

============================= test session starts ==============================
platform linux -- Python 3.13.16, pytest-8.4.2, pluggy-1.6.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content/dfinsight
configfile: pyproject.toml
plugins: platformdirs-4.12.2, anyio-4.15.1, typeguard-4.6.0, langsmith-0.14.2
collected 2 items

dfinsight/tests/test_report.py::test_missing_percentage PASSED           [ 50%]
dfinsight/tests/test_report.py::test_missing_severity PASSED             [100%]

============================== 2 passed in 0.32s ===============================

In [10]:
%%writefile dfinsight/.gitignore

__pycache__/
*.py[cod]
.pytest_cache/
*.egg-info/
build/
dist/
.ipynb_checkpoints/
.venv/
.env

Writing dfinsight/.gitignore

In [11]:
!find dfinsight -maxdepth 3 -type f | sort

dfinsight/dist/dfinsight-0.1.0-py3-none-any.whl
dfinsight/dist/dfinsight-0.1.0.tar.gz
dfinsight/.gitignore
dfinsight/pyproject.toml
dfinsight/.pytest_cache/CACHEDIR.TAG
dfinsight/.pytest_cache/.gitignore
dfinsight/.pytest_cache/README.md
dfinsight/README.md
dfinsight/src/dfinsight.egg-info/dependency_links.txt
dfinsight/src/dfinsight.egg-info/PKG-INFO
dfinsight/src/dfinsight.egg-info/requires.txt
dfinsight/src/dfinsight.egg-info/SOURCES.txt
dfinsight/src/dfinsight.egg-info/top_level.txt
dfinsight/src/dfinsight/__init__.py
dfinsight/src/dfinsight/report.py
dfinsight/tests/__pycache__/test_report.cpython-313-pytest-8.4.2.pyc
dfinsight/tests/test_report.py

In [12]:
!cat dfinsight/README.md

# dfinsight

A lightweight Python library for initial dataset inspection and basic data-quality assessment using pandas.

## Features

- Dataset dimensions
- Data types
- Missing-value counts
- Missing-value percentages
- Missing-value severity
- Duplicate-row detection
- Numeric summary
- Basic issue detection

## Example

```python
import pandas as pd
from dfinsight import quality_report

df = pd.read_csv("data.csv")

quality_report(df)

In [15]:
%%writefile dfinsight/README.md
# dfinsight

A lightweight Python library for initial dataset inspection and basic data-quality assessment using pandas.

## Features

- Dataset dimensions
- Data types
- Missing-value counts
- Missing-value percentages
- Missing-value severity
- Duplicate-row detection
- Numeric summary
- Basic issue detection

## Installation

```bash
pip install dfinsight
````

## Example

```python
import pandas as pd
from dfinsight import quality_report

df = pd.read_csv("data.csv")

quality_report(df)
```

## What it checks

`dfinsight` provides a quick first look at a pandas DataFrame and highlights basic data-quality issues such as:

* Missing values
* High levels of missingness
* Duplicate rows
* Column data types
* Basic numerical statistics

The missing-value severity levels are heuristic indicators intended to support initial dataset investigation.

## Version

0.1.0

Overwriting dfinsight/README.md

In [16]:
!cat dfinsight/README.md

# dfinsight

A lightweight Python library for initial dataset inspection and basic data-quality assessment using pandas.

## Features

- Dataset dimensions
- Data types
- Missing-value counts
- Missing-value percentages
- Missing-value severity
- Duplicate-row detection
- Numeric summary
- Basic issue detection

## Installation

```bash
pip install dfinsight
````

## Example

```python
import pandas as pd
from dfinsight import quality_report

df = pd.read_csv("data.csv")

quality_report(df)
```

## What it checks

`dfinsight` provides a quick first look at a pandas DataFrame and highlights basic data-quality issues such as:

* Missing values
* High levels of missingness
* Duplicate rows
* Column data types
* Basic numerical statistics

The missing-value severity levels are heuristic indicators intended to support initial dataset investigation.

## Version

0.1.0

In [17]:
%%writefile dfinsight/LICENSE
MIT License

Copyright (c) 2026 Muhammad Taqui

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

Writing dfinsight/LICENSE

In [18]:
!ls dfinsight

dist  LICENSE  pyproject.toml  README.md  src  tests

In [19]:
!mkdir -p dfinsight/development

In [20]:
!ls /content

dfinsight  sample_data